name: Maven Run Tests when push to Main branch and newly created PRs.

on:
    # Trigger the workflow on push for the main branch
    # and pull request for main and card-* prefix branches
    push:
        branches:
            - main
        pull_request:
            branches:
                - main
                - # Push events to branches matching refs/heads/card-*
                - 'card-/**'
jobs:
    build:
        runs-on: [ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 18
                uses: actions/setup-java@v1
                with:
                    java-version: 18
            - name: Build with Maven
              run: mvn -B package --file pom.xml
            - name: Test with Maven
              run: mvn -B test --file pom.xml

    

