name: Java CI with Maven single test

on:
  workflow_dispatch:
    inputs:
      class:
        description: 'Test class'
        required: true
      method:
        description: 'Test method'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
      - if: '${{github.event.inputs.class}} == ""'
        run: mvn -Dtest=${{github.event.inputs.class}} -B test --file pom.xml
        run: mvn -Dtest=${{github.event.inputs.class#github.event.inputs.method}} -B test --file pom.xml
